anomaly_detection:
  gamma: 0.1
  nu: 0.05
  output_dir: D:/WORK/project_2004/2406/demo_GUI_train/features
clustering_analysis:
  output_dir: D:/WORK/project_2004/2406/demo_GUI_train/features
data:
  background_dir: data/backgrounds
  background_prob: 0.2
  category_ids:
  - 1
  - 2
  - 3
  train_annotation: data/train/annotations/data.json
  train_image_dir: data/train/images
  val_annotation: data/val/annotations/data.json
  val_image_dir: data/val/images
feature_extraction:
  class_names:
  - background
  - vo
  - than
  - loxo
  model_path: D:/WORK/project_2004/2406/demo_GUI_train/models/best_model.pth
  output_dir: D:/WORK/project_2004/2406/demo_GUI_train/features
  video_dir: D:/WORK/project_2004/2406/demo_GUI_train/videos/train
feature_optimization:
  max_combinations: 1000
  max_features: 10
  min_features: 5
  n_clusters: 4
inference:
  input_video_path: D:/WORK/project_2004/2206/videos/w1.mp4
  model_path: D:/WORK/project_2004/2406/demo_GUI_train/models/best_model.pth
  output_video_path: output/output_segmented.mp4
  result_json_path: output/inference_results.json
  svm_model_path: D:/WORK/project_2004/2406/demo_GUI_train/features/svm_model.npy
model:
  image_size:
  - 256
  - 256
  num_classes: 4
testing:
  colors:
  - - 0
    - 0
    - 0
  - - 0
    - 255
    - 0
  - - 0
    - 0
    - 255
  - - 255
    - 0
    - 0
  - - 255
    - 255
    - 0
  input_video_path: input_video.mp4
  model_path: models/best_model.pth
  output_video_path: output/output_segmented_video.mp4
training:
  batch_size: 4
  best_model_path: models/best_model.pth
  epochs: 50
  last_model_path: models/last_model.pth
  loss: dice
  lr: 0.01
